name: tfm
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311hf197a57_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.2.0=hb27157a_0
  - brotli-bin=1.2.0=h5c1846c_0
  - brotli-python=1.2.0=py311h55b82c4_0
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h26bcf6e_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311haec20ae_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py311h1854d6b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.60.1=py311he13f9b5_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h694c41f_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h6eed73b_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kiwisolver=1.4.9=py311h591569d_2
  - krb5=1.21.3=h37d8d59_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libblas=3.9.0=39_he492b99_openblas
  - libbrotlicommon=1.2.0=h105ed1c_0
  - libbrotlidec=1.2.0=h660c9da_0
  - libbrotlienc=1.2.0=h2338291_0
  - libcblas=3.9.0=39_h9b27e0a_openblas
  - libcxx=21.1.5=h3d58e20_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.9.0=39_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libpng=1.6.50=h84aeda2_1
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.0=h86bffb9_0
  - libtiff=4.7.1=ha0a348c_1
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxgboost=3.1.2=cpu_h4e52287_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.5=h472b3d1_2
  - llvmlite=0.45.1=py311hb26b958_0
  - markupsafe=3.0.3=py311he13f9b5_0
  - matplotlib=3.10.8=py311h6eed73b_0
  - matplotlib-base=3.10.8=py311h48d7e91_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - memory_profiler=0.61.0=pyhcf101f3_1
  - mistune=3.1.4=pyhcf101f3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py311hf901296_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openssl=3.6.0=h230baf5_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hca9a5ca_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py311hc618505_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311h62e9434_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=cpu_pyh053a271_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py311h0e44a47_0
  - pyobjc-framework-cocoa=12.1=py311hbebd54f_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h74c2667_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311he13f9b5_0
  - pyzmq=27.1.0=py311h0ab6910_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.28.0=py311hd2a4513_2
  - scikit-learn=1.7.2=py311had5a2ce_0
  - scipy=1.16.3=py311h32c7e5c_1
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - shap=0.48.0=cpu_py311h9765d02_1
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311ha837bc1_1
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=hf689a15_3
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py311hf197a57_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py311hf197a57_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xgboost=3.1.2=cpu_pyhb39878e_1
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h55e386d_0
  - zstandard=0.25.0=py311h62e9434_1
  - zstd=1.5.7=h8210216_2
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - astunparse==1.6.3
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - namex==0.1.0
      - networkx==3.6
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.18.0
      - propcache==0.4.1
      - protobuf==4.25.8
      - rich==14.2.0
      - sympy==1.14.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.2.0
      - torch==2.2.2
      - torch-geometric==2.7.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/tfm
